create database QL_DiemThi_ver2
go

USE QL_DiemThi_ver2
GO

CREATE TABLE tbl_Account(
	SDT VARCHAR(50) NOT NULL,
	MATKHAU NVARCHAR(50) NOT NULL,
	EMAIL NVARCHAR(50) NOT NULL,
	VAITRO VARCHAR(50) NOT NULL,
	HOTEN NVARCHAR(50) NOT NULL,
	NGAYSINH DATE,
	GIOITINH BIT ,
	QUEQUAN NVARCHAR (100) NOT NULL,
	NGANH NVARCHAR(50) NOT NULL,
	LOP NVARCHAR(50) NOT NULL,
	DSHOCKY NVARCHAR(500) DEFAULT NULL,
	--DIEMTICHLUY FLOAT ,
	AVATAR VARBINARY(MAX) ,
	CONSTRAINT KC1 PRIMARY KEY (SDT)
	)
GO

CREATE TABLE tbl_Class(
	MACLA VARCHAR(50) NOT NULL,
	TENCLA NVARCHAR(50) NOT NULL,
	CONSTRAINT KC2 PRIMARY KEY (MACLA)
	)
GO 

CREATE TABLE tbl_Majors(
	MAMAJ VARCHAR(50) NOT NULL,
	TENMAJ NVARCHAR(50) NOT NULL,
	THUOCKHOA NVARCHAR(50) NOT NULL,
	CONSTRAINT KC3 PRIMARY KEY (MAMAJ)
	)
GO

CREATE TABLE tbl_Subject(
	MASUB VARCHAR(50) NOT NULL,
	TENSUB NVARCHAR(100) NOT NULL,
	CONSTRAINT KC4 PRIMARY KEY (MASUB)
	)
GO


CREATE TABLE tbl_Grade(
    SDT VARCHAR(50) NOT NULL,
    IDMON VARCHAR(50) NOT NULL,
	HOCKY NVARCHAR(50) NOT NULL,
	TENMON NVARCHAR(100) NOT NULL,
	SOTINCHI INT,
	DIEMCC DECIMAL(3, 2) NULL CHECK (DIEMCC <= 10),
	DIEMGK DECIMAL(3, 2) NULL CHECK (DIEMGK <= 10),
	DIEMCK DECIMAL(3, 2) NULL CHECK (DIEMCK <= 10),
	DIEMTBM DECIMAL(3, 2) NULL CHECK (DIEMTBM <= 10),
	GHICHU NVARCHAR(1000) NOT NULL,
    CONSTRAINT KC_Grade PRIMARY KEY (SDT, IDMON, HOCKY),
	CONSTRAINT KN1_Grade FOREIGN KEY (SDT) REFERENCES tbl_Account(SDT),
	CONSTRAINT KN2_Grade FOREIGN KEY (IDMON) REFERENCES tbl_Subject( MASUB)
)
go


INSERT INTO tbl_Account
VALUES  ('1', '1', 'fatroll74@gmail.com', 'admin', N'Bố là admin', '2002-10-29', 1,  '',  '',  '',  NULL, NULL);

INSERT INTO tbl_Account
VALUES  ('0813988966', '1234T', 'tam020386674@huce.edu.vn', 'sv', N'Nguyễn Văn Tâm', '2002-10-29', 1,  '',  '',  '',  NULL, NULL);

DELETE FROM tbl_Account
WHERE SDT = '0813988966'


-- -------------------------------------------------------xóa toàn bộ data base---------------------------------------------------------
DROP TABLE tbl_Majors
DROP TABLE tbl_Class
DROP TABLE tbl_Subject
DROP TABLE tbl_Grade
DROP TABLE tbl_Account
----------------------------------------------------------------------------------------------------------------------------------------




